# Config / meta.yml
meta_title: "RubyRubyRuby"
meta_description: "If you can't beat ruby, join the community."
meta_image: "ruby1.png"  # A picture in your app / assets / images /
twitter_account: "@lewagonadam"  # essential for Twitter Cards
