# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36ac5355f3e713a193e12ca986593db1dc70035f21d88e6f70dfe16d857add4c047f5ce2144d79686b87d223802c570332dc771cf0e2862cdf7d0011fcb07e28

test:
  secret_key_base: 9e566baad61a7a97528f2aead6fe9c3a92b60f0e1d397277556df726b39050945d8abea0cdc74e5493cb7e2b99365c57ac350384adf8077ae2871fe658159753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
